### ISSUE TITLE
Update install feedback to user

### ISSUE THREAD

**Issue by dhalbert** [tekktrik/circfirm#33]
circfirm looks great. I tried using it to update a QT Py ESP32 S2. It failed trying to download
https://downloads.circuitpython.org/bin/adafruit_qt_py_esp32-s2/en_US/adafruit-circuitpython-adafruit_qt_py_esp32-s2-en_US-9.0.0-beta.2.uf2. The board name should be `adafruit_qtpy_esp32s2`.

I assume there are others like this.

**Comment by tekktrik** [comment]
I actually updated things to check `boot_out.txt` first so it can read the board name, then request the device be put in bootloader mode.  The non-bootloader step can now be skipped in the new version (2.0.0) by using `--board` to supply it manually.  I believe this should correct it, let me know!

**Comment by tekktrik** [comment]
And thanks!  It's been on my list of things to push for a while now, so happy be making some major progress as of late!

**Comment by dhalbert** [comment]
I upgraded to circfirm 2.0.2 and now it can't find the device, though the CIRCUITPY drive is available. So should it be able to figure out the board, or should I use `--board`? Thanks.

```sh
$ pipx upgrade-all
upgraded package circfirm from 1.0.1 to 2.0.2 (location: /home/halbert/.local/share/pipx/venvs/circfirm)
$ circfirm install 9.0.0-beta.2
CircuitPython device found, but it is in bootloader mode!
Please put the device out of bootloader mode, or use the --board option.
$ circfirm install 9.0.0-beta.2
CircuitPython device not found!
Check that the device is connected and mounted.
$ ls /media/halbert/CIRCUITPY/
adafruit_us100.py  boot_out.txt  code.py  lib  settings.toml
```

**Comment by tekktrik** [comment]
It should be able to see the `boot_out.txt` file and read the board name from that if you don't use `--board`.  Detection happens by using `psutil` to check for either `boot_out.txt` or `info_uf2.txt`.  Where is the drive located when it's in bootloader mode?  If it's the same place I would expect the detection to work for both.

Just to be sure, `circfirm --version` states it's at 2.0.2 as well, right?

**Comment by tekktrik** [comment]
Also, what Linux distro are you using?  I test with Ubuntu, but if it's something else I wonder if that could be it?

**Comment by tekktrik** [comment]
The only other thing I can think of is that I get this if I connect the board but don't mount it.  I assume it was mounted before the `circfirm` command and not just before the `ls` command, but just trying to brainstorm.

**Comment by dhalbert** [comment]
i am indeed using Now it's working, and I cannot reproduce I wonder if there was some leftover state from the 1.x.x version that it was using.

What happens if you switch boards between "Board name detected" and using circfirm again? (I did not do that.)

I think it would be good to print the name of the board: it's a confirmation for the user.

Also:
```
Downloading UF2...
UF2 file copied to device!
```
There was a long delay in between these messages, and I was wondering if the download was having issues. This is because the status message for downloading is before the action and the status message for copying is after. Could do:
```
Downloading UF2... done
Copying UF2 to adafruit_qtpy_esp32s2... done
```
where there's a delay before the done. But this is all up to you.

**Comment by tekktrik** [comment]
> i am indeed using 2.0.2 on Ubuntu 22.04. Now it's working, and I cannot reproduce I wonder if there was some leftover state from the 1.x.x version that it was using.

Spooky!  Glad it's fixed (or at least not broken 😄) 

> What happens if you switch boards between "Board name detected" and using circfirm again? (I did not do that.)

It will move the UF2 file of the original board to the replacement board.  Right now there isn't really a good way to verify the board once it's in bootloader mode.

> I think it would be good to print the name of the board: it's a confirmation for the user.

Yes!  Good idea!  I like your example output, and think that will be helpful feedback for users.

**Comment by tekktrik** [comment]
Solution should be implemented, thanks for trying this out!
